import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { Buffer } from 'node:buffer';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../', import.meta.url));
const at = (...parts) => resolve(root, ...parts);
const names = ['mark', 'growth', 'focus', 'celebrate'];
const darkPalette = {
  '#39765C': '#8CCBA6',
  '#245C46': '#65AA85',
  '#E1EEE5': '#2B4635',
  '#C8DBC0': '#617F63',
  '#F6F7F2': '#263B2F',
  '#88A87A': '#72946D',
  '#E8B594': '#D8A37C',
  '#4C5140': '#14231B',
  '#DED9BD': '#506C54',
  '#91B8BC': '#638D91',
  '#B9D2D2': '#90B8B8',
};
const artwork = { light: {}, dark: {} };
await mkdir(at('assets/illustrations'), { recursive: true });
await mkdir(at('src/brand'), { recursive: true });
for (const name of names) {
  const svg = await readFile(at(`assets/vectors/${name}.svg`), 'utf8');
  if (/<image\b|base64|<script\b|\bonload\b/i.test(svg))
    throw new Error('Vector source must contain only drawing elements.');
  artwork.light[name] = svg;
  artwork.dark[name] = svg.replace(/#[0-9A-F]{6}/g, (hex) => darkPalette[hex] ?? hex);
  await writeFile(at(`assets/vectors/${name}-dark.svg`), artwork.dark[name]);
  if (name !== 'mark') {
    for (const theme of ['light', 'dark']) {
      const image = sharp(Buffer.from(artwork[theme][name])).resize(1200, 800);
      await image.png().toFile(at(`assets/illustrations/${name}-${theme}.png`));
      await image.webp({ lossless: true }).toFile(at(`assets/illustrations/${name}-${theme}.webp`));
    }
  }
}
const inner = (svg) => svg.replace(/<svg[^>]*>|<\/svg>|<title>.*?<\/title>/gs, '');
function icon({ background = true, dark = false, monochrome = false, size = 644 } = {}) {
  const mark = inner(artwork[dark ? 'dark' : 'light'].mark);
  const drawing = monochrome ? mark.replace(/#[0-9A-F]{6}/g, '#FFFFFF') : mark;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">${background ? `<rect width="1024" height="1024" fill="${dark ? '#131C17' : '#F6F7F2'}"/>` : ''}<svg x="${(1024 - size) / 2}" y="${(1024 - size) / 2}" width="${size}" height="${size}" viewBox="40 80 448 400">${drawing}</svg></svg>`;
}
for (const [name, options] of Object.entries({
  icon: {},
  'icon-dark': { dark: true },
  'adaptive-icon': { background: false, size: 540 },
  'monochrome-icon': { background: false, monochrome: true, size: 540 },
})) {
  const svg = icon(options);
  await writeFile(at(`assets/vectors/${name}.svg`), svg);
  const output = sharp(Buffer.from(svg));
  // iOS App Store icons must be opaque; platform masks their outer corners.
  await (options.background === false ? output : output.flatten())
    .png()
    .toFile(at(`assets/${name}.png`));
}
await writeFile(at('assets/brand.svg'), artwork.light.mark);
await sharp(Buffer.from(icon())).resize(64, 64).flatten().png().toFile(at('assets/favicon.png'));
for (const theme of ['light', 'dark']) {
  const mark = artwork[theme].mark;
  await sharp(Buffer.from(mark))
    .resize(720, 720, { fit: 'contain', background: '#00000000' })
    .png()
    .toFile(at(`assets/${theme === 'light' ? 'splash' : 'splash-dark'}.png`));
}
await writeFile(
  at('src/brand/artwork.ts'),
  '// Generated by pnpm assets:build from assets/vectors. Edit the SVG sources.\nexport const artwork = ' +
    JSON.stringify(artwork, null, 2) +
    ' as const;\n',
);
console.log('Built true SVG artwork, theme variants, platform PNGs and lossless WebP exports.');
